### ISSUE TITLE
Request for Nubia z20

### ISSUE THREAD

**Issue by beforesq** [nullbytepl/device_nubia_TP1803#1]
Hello. I saw you working on pixel experience for nubia devices. Are you able to release any rom for the nubia z20? Their global rom is working really bad... Any rom, it doesnt matter if it has bugs or anything like that... Their rom is running on android 9 and we are almost in 2021...We haven't got a single update..sadly

**Comment by nullbytepl** [comment]
I don't have the device so I can't work on it.
